export const SET_NAME_SURNAME = "SET_NAME_SURNAME";

export const SET_COMPANY = "SET_COMPANY"

export const SET_COUNTRY = "SET_COUNTRY"

export const SET_CITY = "SET_CITY"

export const SET_EMAIL = "SET_EMAIL"

export const SET_ERROR = "SET_ERROR"

export const SET_RECORDS = "SET_RECORDS"

export const RESET_INPUTS = "RESET_INPUTS"

export const SET_SEARCH = "SET_SEARCH"

export const SET_SEARCH_CLASS = "SET_SEARCH_CLASS"

export const CLOSE_INFO = "CLOSE_INFO"

export const SET_FILTERED_RECORDS = "SET_FILTERED_RECORDS"

export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE"

export const CLEAR_SEARCH = "CLEAR_SEARCH"

export const SORT_BY_NAME_ASCENDING = "SORT_BY_NAME_ASCENDING"

export const SORT_BY_NAME_DESCENDING = "SORT_BY_NAME_DESCENDING"

export const SORT_BY_DATE_DESCENDING = "SORT_BY_DATE_DESCENDING"

export const SORT_BY_DATE_ASCENDING = "SORT_BY_DATE_ASCENDING"